version: '3.8'

services:
  # Production environment
  production:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ghcr.io/nanaimo2013/icbc-study-hub:production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

  # Development environment
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/nanaimo2013/icbc-study-hub:dev
    ports:
      - "3001:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Pterodactyl environment
  pterodactyl:
    build:
      context: .
      dockerfile: Dockerfile.pterodactyl
    image: ghcr.io/nanaimo2013/icbc-study-hub:pterodactyl
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - P_SERVER_LOCATION=1
    volumes:
      - pterodactyl_data:/home/container

volumes:
  pterodactyl_data:

networks:
  web:
    driver: bridge 